- ApiToken: ZIBFMU47TKNG6VXCBFLN6EOT
  LicenseKey: x208g9vij6ps9-xv4hbpn9817ms-z7hmqbk8e5dmqe
  Name: windows_test
  Platform: INFRA
  ProductType: SMS
  ProjectCode: 1
- ApiToken: X8OPMF2T8GTID05EG1DPKPYB
  LicenseKey: x20gg9pgpihmq-x3419dfh4vnuve-z32kl85ci2n151
  Name: MasterDB_Test
  Platform: MYSQL
  ProductType: DB
  ProjectCode: 2
- ApiToken: DPHDXNAGGZMA3RHQUZP4LXXT
  LicenseKey: x20ogjq7vrqpe-x7lfb9uh35gpk1-x607q5vj04u3mg
  Name: MASTER_SERVER
  Platform: INFRA
  ProductType: SMS
  ProjectCode: 3
- ApiToken: IC0AJHCZMS1L0F3Q2Z1H22CU
  LicenseKey: x210g42fan77f-z4h7tobj3g1992-z1lsrvgrh0s3q
  Name: SLAVE_SERVER
  Platform: INFRA
  ProductType: SMS
  ProjectCode: 4
- ApiToken: LH3XY6SFUCUTUY96DMAUJN3N
  LicenseKey: x24oga5kc50s5-z6vedc4d13qfni-x7q7qtsgf6sgiq
  Name: nginx_test
  Platform: INFRA
  ProductType: SMS
  ProjectCode: 19
- ApiToken: 2WG6JQQGDDTJK0V2HIOMZ3EF
  LicenseKey: x250gcre7a8ah-x449hscbgsr3p8-z7t66a2922col8
  Name: vCenter_test
  Platform: INFRA
  ProductType: SMS
  ProjectCode: 20
- ApiToken: N0IYB4TB47ODPG9XN4QJJWJ5
  LicenseKey: x258gsms54tne-z6kr0u787sjv97-x3g733p893jlbe
  Name: ee
  Platform: REDIS
  ProductType: DB
  ProjectCode: 21
- ApiToken: JV68Y0FZ15CQU5T3FO1F4AT9
  LicenseKey: x260g6ki12ja0-z20icdbsmqgskm-z6invoosp6iihq
  Name: test
  Platform: INFRA
  ProductType: SMS
  ProjectCode: 24
